[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/spacer/spcr-sdk"
rust-version = "1.80"

[workspace.dependencies]
spcr-utils-crypto = { path = "crates/spcr-utils-crypto", version = "0.1.0" }
