[package]
name = "spcr-utils-crypto"
description = "Cryptographic utilities for the Spacer SDK."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
blake2 = "0.10"
ed25519-dalek = "2"
k256 = { version = "0.13", features = ["ecdsa"] }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
