[package]
name = "spcr-utils-crypto"
description = "Cryptographic utilities for the Spacer SDK."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
